### ISSUE TITLE
RuntimeError: Not running on a RPi!

### ISSUE THREAD

**Issue by espressobeanies** [sbcshop/PiCube#1]
**I keep getting this erro message when running any of the .py scripts from this repository**

Hardware: Raspberry Pi 4 4Gb
OS: Ubuntu MATE 21.10 (impish) aarch64
Python version: 3.9.2

Err response:

```
user@workstation:~/Documents/PiCube$ python3 demo.py
Traceback (most recent call last):
  File "/home/dave/Documents/PiCube/demo.py", line 235, in <module>
    controller = Cube(leds, 0)
  File "/home/dave/Documents/PiCube/demo.py", line 25, in __init__
    GPIO.setup(y, GPIO.OUT)
RuntimeError: Not running on a RPi! 
```

**Comment by Galbi3000** [comment]
I get the exact same error with my Raspberry Pi 5 8Gb running Debian GNU/Linux 12 (bookworm) and Python version 3.11.2

I am trying over an ssh session but have enabled remote GPIO via rasp-config.

It looks like a year and a half and this has not been fixed. Maybe I should not have bought the PiCube!
